/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.ContaDao;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Conta;
import modelo.Usuario;
import modelo.Venda;

/**
 *
 * @author Daiane
 */
public class AddReceber extends javax.swing.JFrame {
    private Usuario usuario;
    private ContaDao contaDao = new ContaDao();
    private Conta contaSelecionada;
    Object p;
    private Venda v = new Venda();
    boolean vend = false;
    boolean alte = false;
    
    /**
     * Creates new form FormPrincipal
     */
    public AddReceber(Usuario usuario) {
        initComponents();
        this.usuario=usuario;
        jPanel6.setPreferredSize(new Dimension(((Double)this.getSize().getWidth()).intValue()-5-5,((Double)this.getSize().getHeight()).intValue()-25-5));
        l_usuario.setText("Usuario: "+ usuario.getNome());
        p = usuario;
    }
    
    public AddReceber(Usuario usuario, Venda venda, String id) {
        initComponents();
        this.usuario=usuario;
        jPanel6.setPreferredSize(new Dimension(((Double)this.getSize().getWidth()).intValue()-5-5,((Double)this.getSize().getHeight()).intValue()-25-5));
        l_usuario.setText("Usuario: "+ usuario.getNome());
        p = usuario;
       
        jtf_valor.setText(venda.getValor());
        vend = false;
        try{
            contaSelecionada = contaDao.buscarPeloId(id);
        }catch (SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao inserir no bd", "Erro", JOptionPane.ERROR_MESSAGE);
        }
       
        v = venda;
        jtf_nome.setText(contaSelecionada.getNome());
        jtf_nascimento.setText(contaSelecionada.getNascimento());
        jtf_cnpj.setText(contaSelecionada.getCnpj());
        jtf_celular.setText(contaSelecionada.getCelular());
        jtf_numero.setText(contaSelecionada.getNumeroNota());
        jtf_valor.setText(venda.getValor());
        jtf_vencimento.setText(contaSelecionada.getDataNota());
        
    }
    
     public AddReceber(Usuario usuario, Venda venda) {
        initComponents();
        this.usuario=usuario;
        jPanel6.setPreferredSize(new Dimension(((Double)this.getSize().getWidth()).intValue()-5-5,((Double)this.getSize().getHeight()).intValue()-25-5));
        l_usuario.setText("Usuario: "+ usuario.getNome());
        p = usuario;
       
        jtf_valor.setText(venda.getValor());
        vend = true;
        this.v = venda;
        contaSelecionada = null;
        
    }
    
    public AddReceber(Usuario usuario, Conta contaSel){
        initComponents();
        this.usuario=usuario;
        p = usuario;
        jPanel6.setPreferredSize(new Dimension(((Double)this.getSize().getWidth()).intValue()-5-5,((Double)this.getSize().getHeight()).intValue()-25-5));
        l_usuario.setText("Usuario: "+ usuario.getNome());
        contaSelecionada = contaSel;
        alte = true;
        jtf_nome.setText(contaSel.getNome());
        if(contaSel.getTipo().equalsIgnoreCase("Física")){
           jr_fisica.setSelected(true);
        }else if(contaSel.getTipo().equalsIgnoreCase("juridica")){
           jr_juridica.setSelected(true);
        }
        jtf_nascimento.setText(contaSel.getNascimento());
        jtf_cnpj.setText(contaSel.getCnpj());
        jtf_celular.setText(contaSel.getCelular());
        jtf_numero.setText(contaSel.getNumeroNota());
        jtf_valor.setText(contaSel.getValorNota());
        jtf_vencimento.setText(contaSel.getDataNota());
        jta_obs.setText(contaSel.getObs());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        l_usuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtf_nome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtf_nascimento = new javax.swing.JTextField();
        jr_fisica = new javax.swing.JRadioButton();
        jr_juridica = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jtf_celular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtf_valor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_obs = new javax.swing.JTextArea();
        btn_salvar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtf_cnpj = new javax.swing.JTextField();
        jtf_numero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtf_vencimento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1020, 750));

        jPanel1.setBackground(new java.awt.Color(5, 5, 5));

        l_usuario.setForeground(new java.awt.Color(255, 255, 0));
        l_usuario.setText("Usuario:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Brush Script MT", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SisTech");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Desenvolvido por Daiane Destri");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 520, Short.MAX_VALUE)
                .addComponent(l_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionando conta à receber:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel6.setMaximumSize(new java.awt.Dimension(1920, 900));
        jPanel6.setMinimumSize(new java.awt.Dimension(1024, 600));
        jPanel6.setPreferredSize(new java.awt.Dimension(1920, 900));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nome do devedor:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Data de nascimento/inicio:");

        buttonGroup1.add(jr_fisica);
        jr_fisica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jr_fisica.setText("Pessoa Física");

        buttonGroup1.add(jr_juridica);
        jr_juridica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jr_juridica.setText("Pessoa Juridica");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Cnpj/Cpf:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Número do documento:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Valor do documento:");

        jta_obs.setColumns(20);
        jta_obs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jta_obs.setRows(5);
        jta_obs.setText("Observação:");
        jScrollPane1.setViewportView(jta_obs);

        btn_salvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_salvar.setText("Enviar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Celular:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Informações sobre o boleto:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/a-pagar.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Data de vencimento:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtf_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jr_fisica)
                                    .addComponent(jr_juridica))
                                .addGap(169, 169, 169))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jtf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(57, 57, 57))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(241, 241, 241))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtf_vencimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_cnpj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                    .addComponent(jtf_valor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                    .addComponent(jtf_numero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(157, 157, 157)
                                        .addComponent(jtf_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addGap(81, 81, 81)))))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_salvar)
                            .addComponent(btn_cancelar))
                        .addGap(56, 56, 56))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jr_fisica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jr_juridica)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_vencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(45, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        if(vend == false){ 
            String nome = jtf_nome.getText();
            String tipo = null;
            if(jr_fisica.isSelected()){
                tipo = "Física";
            }else if(jr_juridica.isSelected()){
                tipo = "juridica";
            }
            String nascimento = jtf_nascimento.getText();
            String cnpj = jtf_cnpj.getText();
            String celular = jtf_celular.getText();
            String numero = jtf_numero.getText();
            String valor = jtf_valor.getText();
            String obs = jta_obs.getText();
            String data = jtf_vencimento.getText();
            String status = "Aberto";
        
            FormPrincipal p1 = new FormPrincipal((Usuario) p);
            if(contaSelecionada == null){
                Conta conta = new Conta(nome,nascimento,tipo,cnpj,celular,numero,valor,obs, data);
            
                try{
                    contaDao.adicionar(conta);
                    JOptionPane.showMessageDialog(null, "Conta à receber adicionada");
                    this.dispose();
                    p1.setVisible(true);
                    //limparCampos();
                
                }catch (SQLException ex){
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Erro ao inserir no bd", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }else if(alte == true){
                contaSelecionada.setNome(nome);
                contaSelecionada.setNascimento(nascimento);
                contaSelecionada.setTipo(tipo);
                contaSelecionada.setCnpj(cnpj);
                contaSelecionada.setCelular(celular);
                contaSelecionada.setNumeroNota(numero);
                contaSelecionada.setValorNota(valor);
                contaSelecionada.setDataNota(data);
                contaSelecionada.setObs(obs);
                try{
                    contaDao.alterar(contaSelecionada);
                    JOptionPane.showMessageDialog(null, "Conta alterada");
                    this.dispose();
                    p1.setVisible(true);

                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            
            }else{
                contaSelecionada.setNome(nome);
                contaSelecionada.setNascimento(nascimento);
                contaSelecionada.setTipo(tipo);
                contaSelecionada.setCnpj(cnpj);
                contaSelecionada.setCelular(celular);
                contaSelecionada.setNumeroNota(numero);
                contaSelecionada.setValorNota(valor);
                contaSelecionada.setDataNota(data);
                contaSelecionada.setObs(obs);
            
                try{
                    contaDao.alterar(contaSelecionada);
                    JOptionPane.showMessageDialog(null, "Conta alterada");
                    Boolean alt = true;
                    AddVenda vd = new AddVenda(usuario, contaSelecionada, v, alt);
                    this.dispose();
                    p1.setVisible(true);

                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            
            }
        }else if(vend == true){
            String nome = jtf_nome.getText();
            String tipo = null;
            if(jr_fisica.isSelected()){
                tipo = "Física";
            }else if(jr_juridica.isSelected()){
                tipo = "juridica";
            }
            String nascimento = jtf_nascimento.getText();
            String cnpj = jtf_cnpj.getText();
            String celular = jtf_celular.getText();
            String numero = jtf_numero.getText();
            String valor = jtf_valor.getText();
            String obs = jta_obs.getText();
            String data = jtf_vencimento.getText();
            String status = "Aberto";
        
            //AddVenda venda1 = new AddVenda(usuario, v);
            if(contaSelecionada == null){
                Conta conta = new Conta(nome,nascimento,tipo,cnpj,celular,numero,valor,obs, data);
            
                try{
                    contaDao.adicionar(conta);
                    JOptionPane.showMessageDialog(null, "Conta à receber adicionada");
                    this.dispose();

                    Conta c = (Conta) contaDao.buscarUltima();
                    AddVenda vd = new AddVenda(usuario, c, v);
                    //vd.setVisible(true);
                    //limparCampos();
                
                }catch (SQLException ex){
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Erro ao inserir no bd", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
        FormPrincipal p1 = new FormPrincipal((Usuario) p);
        p1.setVisible(true);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jr_fisica;
    private javax.swing.JRadioButton jr_juridica;
    private javax.swing.JTextArea jta_obs;
    private javax.swing.JTextField jtf_celular;
    private javax.swing.JTextField jtf_cnpj;
    private javax.swing.JTextField jtf_nascimento;
    private javax.swing.JTextField jtf_nome;
    private javax.swing.JTextField jtf_numero;
    private javax.swing.JTextField jtf_valor;
    private javax.swing.JTextField jtf_vencimento;
    private javax.swing.JLabel l_usuario;
    // End of variables declaration//GEN-END:variables
}
