/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import dao.VendaDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Conta;
import modelo.Usuario;
import modelo.Venda;

/**
 *
 * @author Daiane
 */
public class AddVenda extends javax.swing.JFrame {
    private Usuario usuario;
    Object p;
    float valor;
    private Venda venda = new Venda();
    private VendaDao vendaDao = new VendaDao();
    private String id;
    private boolean alt = false; 
    private boolean con = false;
    /**
     * Creates new form AddVenda
     */
    public AddVenda(Usuario usu) {
        //this.vendaDao = null;
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario=usu;
        l_usuario.setText("Usuario: "+ usuario.getNome());
        p = usuario;
    }
    
    public AddVenda(Usuario usu, Conta c, Venda venda) throws SQLException {
        //this.vendaDao = null;
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario=usu;
        l_usuario.setText("Usuario: "+ usuario.getNome());
        p = usuario;
        
        String cid = Integer.toString(c.getCod());
        venda.setContaId(cid);
        vendaDao.adicionar(venda);
        FormPrincipal p1 = new FormPrincipal(usu);
        //p1.setExtendedState(p1.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        p1.setVisible(true);
    }
    
    public AddVenda(Usuario usu, Conta c, Venda venda, Boolean v){
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario=usu;
        l_usuario.setText("Usuario: "+ usuario.getNome());
        p = usuario;
        
//        JOptionPane.showMessageDialog(null, venda.getId(), "Erro", JOptionPane.ERROR_MESSAGE);
        try{
            vendaDao.alterar(venda);      
        }catch (SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao alterar no bd", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    public AddVenda(Usuario usu,Venda ven, int id){
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario=usu;
        l_usuario.setText("Usuario: "+ usuario.getNome());
        p = usuario;
        
        this.venda = ven;
        venda.setId(id);
    }

    public AddVenda(Usuario usu, Venda vendaSelecionada){
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario=usu;
        l_usuario.setText("Usuario: "+ usuario.getNome());
        p = usuario;
        alt = true;
        
        if(vendaSelecionada.getErp().equalsIgnoreCase("true")){
            check_erp.setSelected(true);         
        }
        if(vendaSelecionada.getScm().equalsIgnoreCase("true")){
            check_scm.setSelected(true);
        }
        if(vendaSelecionada.getCrm().equalsIgnoreCase("true")){
            check_crm.setSelected(true);
        }
        if(vendaSelecionada.getSig().equalsIgnoreCase("true")){
            check_sig.setSelected(true);
        }
        if(vendaSelecionada.getAcomp().equalsIgnoreCase("true")){
            jrb_acomp.setSelected(true);
        }
        if(vendaSelecionada.getAcomp().equalsIgnoreCase("false")){
            jrb_semAcomp.setSelected(true);
        }
        if(vendaSelecionada.getTrein().equalsIgnoreCase("true")){
            jrb_trein.setSelected(true);
        }
        if(vendaSelecionada.getTrein().equalsIgnoreCase("false")){
            jrb_semTrein.setSelected(true);
        }
        if(vendaSelecionada.getSup().equalsIgnoreCase("Sem suporte")){
            jrb_semSup.setSelected(true);
        }
        if(vendaSelecionada.getSup().equalsIgnoreCase("Suporte inteiro")){
            jrb_supInt.setSelected(true);
        }
        if(vendaSelecionada.getSup().equalsIgnoreCase("Suporte parcial")){
            jrb_supPar.setSelected(true);
        }
        
        id = vendaSelecionada.getContaId();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jrb_fechar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtf_valorTotal = new javax.swing.JTextField();
        btn_limpar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        l_usuario = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jrb_trein = new javax.swing.JRadioButton();
        jrb_semTrein = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jrb_supInt = new javax.swing.JRadioButton();
        jrb_supPar = new javax.swing.JRadioButton();
        jrb_semSup = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jrb_acomp = new javax.swing.JRadioButton();
        jrb_semAcomp = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        check_erp = new javax.swing.JCheckBox();
        check_crm = new javax.swing.JCheckBox();
        check_scm = new javax.swing.JCheckBox();
        check_sig = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_calcular = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jrb_fechar.setText("Fechar  venda");
        jrb_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_fecharActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Total:");

        jtf_valorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_valorTotalActionPerformed(evt);
            }
        });

        btn_limpar.setText("Limpar campos");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(5, 5, 5));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Brush Script MT", 2, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SisTech");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Desenvolvido por Daiane Destri");

        l_usuario.setForeground(new java.awt.Color(255, 255, 0));
        l_usuario.setText("Usuario:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(l_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Deseja obter treinamento inicial?");

        buttonGroup1.add(jrb_trein);
        jrb_trein.setText("Sim - R$200,00");
        jrb_trein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_treinActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrb_semTrein);
        jrb_semTrein.setText("Não - R$0,0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_semTrein)
                            .addComponent(jrb_trein)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_trein)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_semTrein)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Selecione o tipo de suporte que deseja?");

        buttonGroup3.add(jrb_supInt);
        jrb_supInt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrb_supInt.setText("Com suporte integral R$170,00");

        buttonGroup3.add(jrb_supPar);
        jrb_supPar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrb_supPar.setText("Com suporte parcial R$100,00");

        buttonGroup3.add(jrb_semSup);
        jrb_semSup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrb_semSup.setText("Sem suporte R$0,0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_semSup)
                            .addComponent(jrb_supPar)
                            .addComponent(jrb_supInt)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_supInt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_supPar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_semSup)
                .addGap(14, 14, 14))
        );

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        buttonGroup2.add(jrb_acomp);
        jrb_acomp.setText("Sim - R$1000,00 + despesas");
        jrb_acomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_acompActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrb_semAcomp);
        jrb_semAcomp.setText("Não - R$0,0");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Deseja obter acompanhamento especializado?");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jrb_semAcomp))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jrb_acomp))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_acomp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_semAcomp)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Quais sistemas será adquirido?");

        check_erp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        check_erp.setText("E.R.P - R$8.000,00");

        check_crm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        check_crm.setText("C.R.M - R$7.000,00");

        check_scm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        check_scm.setText("S.C.M - R$10.000,00");
        check_scm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_scmActionPerformed(evt);
            }
        });

        check_sig.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        check_sig.setText("S.I.G - R$9.000,00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_erp)
                    .addComponent(check_crm))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_scm)
                    .addComponent(check_sig))
                .addGap(52, 52, 52))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_erp)
                    .addComponent(check_scm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_crm)
                    .addComponent(check_sig))
                .addGap(17, 17, 17))
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VENDA");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(433, 433, 433)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/caixa-eletronico.png"))); // NOI18N

        btn_calcular.setText("Calcular valor");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel10.setText("ATENÇÃO: O valor dos suportes será calculado para");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel11.setText("cada sistema selecionado!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jrb_fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel11)))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jrb_fechar)
                    .addComponent(btn_limpar)
                    .addComponent(jButton3)
                    .addComponent(btn_calcular))
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_acompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_acompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_acompActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        check_erp.setSelected(false);
        check_crm.setSelected(false);
        check_scm.setSelected(false);
        check_sig.setSelected(false);
        
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        
        jtf_valorTotal.setText("");
        valor = 0;
    }//GEN-LAST:event_btn_limparActionPerformed

    private void jtf_valorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_valorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_valorTotalActionPerformed

    private void jrb_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_fecharActionPerformed
        if(con == true && jtf_valorTotal.getText() != ""){
            String erp = "false";
            String crm = "false";
            String scm = "false";
            String sig = "false";
            String sup = null;
            String acomp = "false";
            String trein = "false";
            String valorTotal;
           // VendaDao vendaDao = null;
            //TIPOS DE SISTEMAS
            if(check_erp.isSelected()){
                erp = "true";
            }
            if(check_crm.isSelected()){
                crm = "true";
            }
            if(check_scm.isSelected()){
                scm = "true";
            }
            if(check_sig.isSelected()){
                sig = "true";
            }
            
            //SUPORTE
            if(jrb_supInt.isSelected()){
                sup = "Integral";
            }else if(jrb_supPar.isSelected()){
                sup = "Parcial";
            }else if(jrb_semSup.isSelected()){
                sup = "Sem suporte";
            }
            
            //ACOMPANHAMENTO
            if(jrb_acomp.isSelected()){
                acomp = "true";
            }else if(jrb_semAcomp.isSelected()){
                acomp = "false";
            }
            
            //TREINAMENTO
            if(jrb_trein.isSelected()){
                trein = "true";
            }else if(jrb_semTrein.isSelected()){
                trein = "false";
            }
            
            valorTotal = jtf_valorTotal.getText();
        
            if(alt == false){
                venda.setErp(erp);
                venda.setScm(scm);
                venda.setCrm(crm);
                venda.setSig(sig);
                venda.setAcomp(acomp);
                venda.setTrein(trein);
                venda.setSup(sup);
                venda.setValor(valorTotal);
                venda.setContaId("1");
     
                AddReceber rec = new AddReceber(usuario,venda);
                rec.setExtendedState(rec.getExtendedState()|JFrame.MAXIMIZED_BOTH);
                this.dispose();
                rec.setVisible(true);
            }else if(alt == true){
                venda.setErp(erp);
                venda.setScm(scm);
                venda.setCrm(crm);
                venda.setSig(sig);
                venda.setAcomp(acomp);
                venda.setTrein(trein);
                venda.setSup(sup);
                venda.setValor(valorTotal);
                venda.setContaId(id);
            
                try{
                    vendaDao.alterar(venda); 
                }catch (SQLException ex){
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Erro ao inserir no bd", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            
                AddReceber rec = new AddReceber(usuario,venda, id);
                rec.setExtendedState(rec.getExtendedState()|JFrame.MAXIMIZED_BOTH);
                this.dispose();
                rec.setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Calcule o valor total primeiro.", "Erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jrb_fecharActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         this.dispose();
        FormPrincipal p1 = new FormPrincipal((Usuario) p);
        p1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jrb_treinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_treinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_treinActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        con = true;
        valor = 0;
        //TIPOS DE SISTEMAS
        int t = 0;
        if(check_erp.isSelected()){
            valor = valor + 8000;
            t = t + 1;
        }
        if(check_crm.isSelected()){
            valor = valor + 7000;
            t = t + 1;
        }
        if(check_scm.isSelected()){
            valor = valor + 10000;
            t = t + 1;
        }
        if(check_sig.isSelected()){
            valor = valor + 9000;
            t = t + 1;
        }
        
        //SUPORTE
        if(jrb_supInt.isSelected()){
            if(t > 1){
                float v1 = t * 170;
                valor = valor + v1;
            }else if(t == 1){
                valor = valor + 170; 
            }else{
                //
            }
           
        }
        if(jrb_supPar.isSelected()){
            if(t > 1){
                float v1 = t * 100;
                valor = valor + v1;
            }else if(t == 1){
                valor = valor + 100; 
            }else{
                //
            }
        }
        if(jrb_semSup.isSelected()){
            valor = valor + 0;
        }
        
        //ACOMPANHAMENTO
        if(jrb_acomp.isSelected()){
            if(t > 1){
                float v1 = t * 1000;
                valor = valor + v1;
            }else if(t == 1){
                valor = valor + 1000; 
            }else{
                //
            }
            //valor = valor + 1000;
        }
        if(jrb_semAcomp.isSelected()){
            valor = valor + 0;
        }
        
        //TREINAMENTO
        if(jrb_trein.isSelected()){
            if(t > 1){
                float v1 = t * 200;
                valor = valor + v1;
            }else if(t == 1){
                valor = valor + 200; 
            }else{
                //
            }
            //valor = valor + 200;
        }
        if(jrb_semTrein.isSelected()){
            valor = valor + 0;
        }
       
        
        String valorCon = Float.toString(valor);
        jtf_valorTotal.setText(valorCon);
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void check_scmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_scmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_scmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_limpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox check_crm;
    private javax.swing.JCheckBox check_erp;
    private javax.swing.JCheckBox check_scm;
    private javax.swing.JCheckBox check_sig;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jrb_acomp;
    private javax.swing.JButton jrb_fechar;
    private javax.swing.JRadioButton jrb_semAcomp;
    private javax.swing.JRadioButton jrb_semSup;
    private javax.swing.JRadioButton jrb_semTrein;
    private javax.swing.JRadioButton jrb_supInt;
    private javax.swing.JRadioButton jrb_supPar;
    private javax.swing.JRadioButton jrb_trein;
    private javax.swing.JTextField jtf_valorTotal;
    private javax.swing.JLabel l_usuario;
    // End of variables declaration//GEN-END:variables
}
