/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JFrame;
import modelo.Usuario;

/**
 *
 * @author Daiane
 */
public class FormPrincipal extends javax.swing.JFrame {
    private Usuario usuario;
    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal(Usuario usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario=usuario;
        l_usuario.setText("Usuario: "+ usuario.getNome());
     
        controleNivelAcesso();
    }
    
     private void controleNivelAcesso(){
        if(usuario.getNivel().equals("admin")){
            //this.j_menu_manutencao.setVisible(true);
            //this.j_menu_relatorio.setVisible(true);
        }else{
            this.jPanel5.setVisible(false);
            //this.j_menu_funcionario.setVisible(false);
            //this.j_menu_relatorio.setVisible(false);
            this.menu_addUsuarios.setVisible(false);
            this.menu_relUsuarios.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        l_usuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_addPagar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_addreceber = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_addVenda = new javax.swing.JButton();
        btn_opcoesVenda = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_relatorioReceber = new javax.swing.JButton();
        btn_relatorioPagar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_adusu = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menu_addVenda = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menu_relContasReceber = new javax.swing.JMenuItem();
        menu_relContasPagar = new javax.swing.JMenuItem();
        menu_relVendas = new javax.swing.JMenuItem();
        menu_relUsuarios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_addReceber = new javax.swing.JMenuItem();
        menu_addPagar = new javax.swing.JMenuItem();
        menu_addUsuarios = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menu_sobre = new javax.swing.JMenuItem();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jPanel1.setBackground(new java.awt.Color(5, 5, 5));

        l_usuario.setForeground(new java.awt.Color(255, 255, 0));
        l_usuario.setText("Usuário:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Brush Script MT", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SisTech");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Desenvolvido por Daiane Destri");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.setToolTipText("");

        btn_addPagar.setForeground(new java.awt.Color(7, 0, 255));
        btn_addPagar.setText("Adicionar contas à pagar");
        btn_addPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addPagarActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/despesas.png"))); // NOI18N

        btn_addreceber.setForeground(new java.awt.Color(7, 0, 255));
        btn_addreceber.setText("Adicionar contas à receber");
        btn_addreceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addreceberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_addPagar)
                    .addComponent(btn_addreceber))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_addreceber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_addPagar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vendas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.setToolTipText("");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/conta.png"))); // NOI18N

        btn_addVenda.setForeground(new java.awt.Color(7, 0, 255));
        btn_addVenda.setText("Adicionar vendas");
        btn_addVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addVendaActionPerformed(evt);
            }
        });

        btn_opcoesVenda.setForeground(new java.awt.Color(7, 0, 255));
        btn_opcoesVenda.setText("Relatório de vendas");
        btn_opcoesVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opcoesVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_addVenda)
                    .addComponent(btn_opcoesVenda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_addVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_opcoesVenda)))
                .addGap(21, 21, 21))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relatórios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel4.setToolTipText("");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/relatorio.png"))); // NOI18N

        btn_relatorioReceber.setForeground(new java.awt.Color(7, 0, 255));
        btn_relatorioReceber.setText("Relatório contas à receber");
        btn_relatorioReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_relatorioReceberActionPerformed(evt);
            }
        });

        btn_relatorioPagar.setForeground(new java.awt.Color(7, 0, 255));
        btn_relatorioPagar.setText("Relatório contas à pagar");
        btn_relatorioPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_relatorioPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_relatorioReceber)
                    .addComponent(btn_relatorioPagar))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_relatorioReceber)
                        .addGap(18, 18, 18)
                        .addComponent(btn_relatorioPagar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel5.setToolTipText("");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/companhia.png"))); // NOI18N

        btn_adusu.setForeground(new java.awt.Color(7, 0, 255));
        btn_adusu.setText("Cadastrar Usuários");
        btn_adusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adusuActionPerformed(evt);
            }
        });

        jButton8.setForeground(new java.awt.Color(7, 0, 255));
        jButton8.setText("Relatório Usuários");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_adusu)
                    .addComponent(jButton8))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_adusu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addGap(18, 18, 18))
        );

        jMenu2.setText("Vendas");

        menu_addVenda.setText("Adicionar Vendas");
        menu_addVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_addVendaActionPerformed(evt);
            }
        });
        jMenu2.add(menu_addVenda);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Relatórios");

        menu_relContasReceber.setText("Relatório contas à receber");
        menu_relContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_relContasReceberActionPerformed(evt);
            }
        });
        jMenu5.add(menu_relContasReceber);

        menu_relContasPagar.setText("Relatório contas à pagar");
        menu_relContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_relContasPagarActionPerformed(evt);
            }
        });
        jMenu5.add(menu_relContasPagar);

        menu_relVendas.setText("Relatório de vendas");
        menu_relVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_relVendasActionPerformed(evt);
            }
        });
        jMenu5.add(menu_relVendas);

        menu_relUsuarios.setText("Relatório Usuários");
        menu_relUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_relUsuariosActionPerformed(evt);
            }
        });
        jMenu5.add(menu_relUsuarios);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Manutenção");

        menu_addReceber.setText("Adicionar contas à receber");
        menu_addReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_addReceberActionPerformed(evt);
            }
        });
        jMenu3.add(menu_addReceber);

        menu_addPagar.setText("Adicionar contas à pagar");
        menu_addPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_addPagarActionPerformed(evt);
            }
        });
        jMenu3.add(menu_addPagar);

        menu_addUsuarios.setText("Adicionar usuários");
        menu_addUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_addUsuariosActionPerformed(evt);
            }
        });
        jMenu3.add(menu_addUsuarios);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sobre");

        menu_sobre.setText("Informações sobre o sistema");
        menu_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sobreActionPerformed(evt);
            }
        });
        jMenu4.add(menu_sobre);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(519, 519, 519)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addVendaActionPerformed
        AddVenda ven = new AddVenda(usuario);
        this.dispose();
        //ven.setExtendedState(ven.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        ven.setVisible(true);
        
    }//GEN-LAST:event_btn_addVendaActionPerformed

    private void btn_opcoesVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opcoesVendaActionPerformed
        RelatorioVenda ven = new RelatorioVenda(usuario);
        this.dispose();
        ven.setExtendedState(ven.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        ven.setVisible(true);
    }//GEN-LAST:event_btn_opcoesVendaActionPerformed

    private void btn_adusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adusuActionPerformed
        AddUsuario adu = new AddUsuario(usuario);
        this.dispose();
        //adu.setExtendedState(adu.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        adu.setVisible(true);
    }//GEN-LAST:event_btn_adusuActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        RelatoriosUsu rus = new RelatoriosUsu(usuario);
        this.dispose();
        rus.setVisible(true);
        rus.setExtendedState(rus.getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btn_addreceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addreceberActionPerformed
        AddReceber adr= new AddReceber(usuario);
        this.dispose();
        adr.setExtendedState(adr.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        adr.setVisible(true);
    }//GEN-LAST:event_btn_addreceberActionPerformed

    private void btn_addPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addPagarActionPerformed
        AddPagar adr= new AddPagar(usuario);
        this.dispose();
        adr.setExtendedState(adr.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        adr.setVisible(true);
    }//GEN-LAST:event_btn_addPagarActionPerformed

    private void btn_relatorioReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_relatorioReceberActionPerformed
        Relatorios rel = new Relatorios(usuario);
        this.dispose();
        rel.setExtendedState(rel.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        rel.setVisible(true);
    }//GEN-LAST:event_btn_relatorioReceberActionPerformed

    private void btn_relatorioPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_relatorioPagarActionPerformed
        RelatoriosP rel = new RelatoriosP(usuario);
        this.dispose();
        rel.setExtendedState(rel.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        rel.setVisible(true);
    }//GEN-LAST:event_btn_relatorioPagarActionPerformed

    private void menu_addVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_addVendaActionPerformed
        AddVenda ven = new AddVenda(usuario);
        this.dispose();
        //ven.setExtendedState(ven.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        ven.setVisible(true);
    }//GEN-LAST:event_menu_addVendaActionPerformed

    private void menu_addReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_addReceberActionPerformed
        AddReceber adr= new AddReceber(usuario);
        this.dispose();
        adr.setExtendedState(adr.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        adr.setVisible(true);
    }//GEN-LAST:event_menu_addReceberActionPerformed

    private void menu_addPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_addPagarActionPerformed
        AddPagar adr= new AddPagar(usuario);
        this.dispose();
        adr.setExtendedState(adr.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        adr.setVisible(true);
    }//GEN-LAST:event_menu_addPagarActionPerformed

    private void menu_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sobreActionPerformed
        Sobre s = new Sobre(usuario);
        this.dispose();
        s.setVisible(true);
    }//GEN-LAST:event_menu_sobreActionPerformed

    private void menu_relContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_relContasReceberActionPerformed
        Relatorios rl = new Relatorios(usuario);
        this.dispose();
        rl.setExtendedState(rl.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        rl.setVisible(true);
    }//GEN-LAST:event_menu_relContasReceberActionPerformed

    private void menu_relContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_relContasPagarActionPerformed
        RelatoriosP rlp = new RelatoriosP(usuario);
        this.dispose();
        rlp.setExtendedState(rlp.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        rlp.setVisible(true);
    }//GEN-LAST:event_menu_relContasPagarActionPerformed

    private void menu_relVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_relVendasActionPerformed
        RelatorioVenda rlv = new RelatorioVenda(usuario);
        this.dispose();
        rlv.setExtendedState(rlv.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        rlv.setVisible(true);
    }//GEN-LAST:event_menu_relVendasActionPerformed

    private void menu_addUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_addUsuariosActionPerformed
        AddUsuario adu = new AddUsuario(usuario);
        this.dispose();
        adu.setVisible(true);
    }//GEN-LAST:event_menu_addUsuariosActionPerformed

    private void menu_relUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_relUsuariosActionPerformed
        RelatoriosUsu rus = new RelatoriosUsu(usuario);
        this.dispose();
        rus.setVisible(true);
        rus.setExtendedState(rus.getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_menu_relUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addPagar;
    private javax.swing.JButton btn_addVenda;
    private javax.swing.JButton btn_addreceber;
    private javax.swing.JButton btn_adusu;
    private javax.swing.JButton btn_opcoesVenda;
    private javax.swing.JButton btn_relatorioPagar;
    private javax.swing.JButton btn_relatorioReceber;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel l_usuario;
    private javax.swing.JMenuItem menu_addPagar;
    private javax.swing.JMenuItem menu_addReceber;
    private javax.swing.JMenuItem menu_addUsuarios;
    private javax.swing.JMenuItem menu_addVenda;
    private javax.swing.JMenuItem menu_relContasPagar;
    private javax.swing.JMenuItem menu_relContasReceber;
    private javax.swing.JMenuItem menu_relUsuarios;
    private javax.swing.JMenuItem menu_relVendas;
    private javax.swing.JMenuItem menu_sobre;
    // End of variables declaration//GEN-END:variables
}
