/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.ContaDao;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Conta;
import modelo.Usuario;

/**
 *
 * @author Daiane
 */
public class RelatoriosP extends javax.swing.JFrame {
    private Usuario usuario;
    private ContaDao contaDao = new ContaDao();
    private List<Conta> contasR;
    private Conta contaSelecionada;
    Object p;
    
    /**
     * Creates new form FormPrincipal
     */
    public RelatoriosP(Usuario usuario) {
        initComponents();
        this.usuario=usuario;
        jPanel6.setPreferredSize(new Dimension(((Double)this.getSize().getWidth()).intValue()-5-5,((Double)this.getSize().getHeight()).intValue()-25-5));
        l_usuario.setText("Usuario: "+ usuario.getNome());
        p = usuario;
        atualizarTabela();
        
        if(usuario.getNivel().equalsIgnoreCase("Funcionario")){
            btn_abrir.setEnabled(false);
        }
       
    }
    
 
    private void atualizarTabela() {
        try {
            contasR = contaDao.buscarPelaDescricaoP(jtf_pesquisa.getText());

            DefaultTableModel model = (DefaultTableModel) tabela.getModel();
            model.setNumRows(0);
            for (int i = 0; i < contasR.size(); i++) {
                Conta conta = contasR.get(i);
                model.addRow(new Object[]{conta.getCod(), conta.getStatus(), conta.getNome(),conta.getNascimento(),conta.getTipo(), conta.getCnpj(), conta.getCelular(), conta.getNumeroNota(), conta.getValorNota(), conta.getDataNota()});
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        l_usuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jtf_pesquisa = new javax.swing.JTextField();
        btn_pesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_excluir = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_fechar = new javax.swing.JButton();
        btn_atualizar = new javax.swing.JButton();
        btn_abrir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(5, 5, 5));

        l_usuario.setForeground(new java.awt.Color(255, 255, 0));
        l_usuario.setText("Usuario:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Brush Script MT", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SisTech");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Desenvolvido por Daiane Destri");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(317, 317, 317)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relatório:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel6.setMaximumSize(new java.awt.Dimension(1920, 900));
        jPanel6.setMinimumSize(new java.awt.Dimension(1024, 600));
        jPanel6.setPreferredSize(new java.awt.Dimension(1920, 900));

        jtf_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_pesquisaActionPerformed(evt);
            }
        });

        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_fechar.setText("Fechar conta");
        btn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharActionPerformed(evt);
            }
        });

        btn_atualizar.setText("Atualizar tabela");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        btn_abrir.setText("Abrir conta");
        btn_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrirActionPerformed(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_excluir)
                .addGap(56, 56, 56)
                .addComponent(btn_alterar)
                .addGap(44, 44, 44)
                .addComponent(btn_fechar)
                .addGap(38, 38, 38)
                .addComponent(btn_abrir)
                .addGap(36, 36, 36)
                .addComponent(btn_atualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_excluir)
                    .addComponent(btn_alterar)
                    .addComponent(btn_fechar)
                    .addComponent(btn_atualizar)
                    .addComponent(btn_abrir)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Status", "Nome", "Nascimento", "Tipo", "Cnpj/Cpf", "Celular", "Número", "Valor", "Vencimento"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jtf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_pesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pesquisar))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_pesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_pesquisaActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int linha = tabela.getSelectedRow();
        if(linha < 0){
            JOptionPane.showMessageDialog(null, "Selecione uma pessoa", "Atenção",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        contaSelecionada = contasR.get(linha);
        int cod = contasR.get(linha).getCod();
        try {
            contaDao.removerP(cod);
            JOptionPane.showMessageDialog(null, "Conta excluída");
            atualizarTabela();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        atualizarTabela();
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed
        int linha = tabela.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma conta", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        contaSelecionada = contasR.get(linha);
        AddPagar adr = new AddPagar(usuario, contaSelecionada);
        this.dispose();
        adr.setExtendedState(adr.getExtendedState()|JFrame.MAXIMIZED_BOTH);        
        adr.setVisible(true);
        
//
//        pessoaSelecionada = pessoas.get(linha);
//        jtf_nome.setText(pessoaSelecionada.getNome());
//        if(pessoaSelecionada.getSexo().equalsIgnoreCase("feminino")){
//            jrb_feminino.setSelected(true);
//        }else if(pessoaSelecionada.getSexo().equalsIgnoreCase("masculino")){
//            jtb_masculino.setSelected(true);
//        }
//        jtf_bairro.setText(pessoaSelecionada.getBairro());
//        jtf_endereco.setText(pessoaSelecionada.getEndereco());
//        jtf_cep.setText(pessoaSelecionada.getCep());
//        jtf_cpf.setText(pessoaSelecionada.getCep());
//        jtf_nascimento.setText(pessoaSelecionada.getNascimento());
//        jtf_vencimento.setText(pessoaSelecionada.getVencimento());
//        jtf_unidade.setText(pessoaSelecionada.getUnidade());
//        jtf_email.setText(pessoaSelecionada.getEmail());
//        jtf_kwh.setText(pessoaSelecionada.getKwh());
//        jtf_valorTotal.setText(pessoaSelecionada.getTotal());
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharActionPerformed
        try {
            int linha = tabela.getSelectedRow();
            if (linha < 0) {
                JOptionPane.showMessageDialog(null, "Selecione uma conta", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            contaSelecionada = contasR.get(linha);
            contaSelecionada.setStatus("Fechado");
            //JOptionPane.showMessageDialog(null,contaSelecionada.getStatus() + contaSelecionada.getNome(), "Atenção", JOptionPane.WARNING_MESSAGE);
            //try {
            contaDao.alterarP(contaSelecionada);
            //} catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "Erro ao alterar o status da conta", "Atenção", JOptionPane.WARNING_MESSAGE);
            //}
            atualizarTabela();
        } catch (SQLException ex) {
            Logger.getLogger(RelatoriosP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_fecharActionPerformed

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        atualizarTabela();
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        String descricao = jtf_pesquisa.getText();
        try {
            contasR = contaDao.buscarPelaDescricaoP(descricao);
        } catch (SQLException ex) {
            Logger.getLogger(RelatoriosP.class.getName()).log(Level.SEVERE, null, ex);
        }
        atualizarTabela();
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void btn_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrirActionPerformed
        try {
            int linha = tabela.getSelectedRow();
            if (linha < 0) {
                JOptionPane.showMessageDialog(null, "Selecione uma conta", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            contaSelecionada = contasR.get(linha);
            contaSelecionada.setStatus("Aberto");
            //JOptionPane.showMessageDialog(null,contaSelecionada.getStatus() + contaSelecionada.getNome(), "Atenção", JOptionPane.WARNING_MESSAGE);
            //try {
            contaDao.alterarP(contaSelecionada);
            //} catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "Erro ao alterar o status da conta", "Atenção", JOptionPane.WARNING_MESSAGE);
            //}
            atualizarTabela();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar o status da conta", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_abrirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        FormPrincipal p1 = new FormPrincipal((Usuario) p);
        p1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_abrir;
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_fechar;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtf_pesquisa;
    private javax.swing.JLabel l_usuario;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
